// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UnityEditor;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

[Serializable]
public abstract class MenuCanvas : MonoBehaviour
{
    #region Abstract Methods
    public abstract GameObject GetFirstButton();
    public abstract AssetEnum GetAssetEnum();
    #endregion
    [SerializeField]
    private RectTransform mainButtonsContainer;
    [SerializeField]
    private RectTransform[] generatedWidgetContainers;
    private LayoutGroup _layoutGroup;
    private const int MaxCheckLayoutTimeout = 2;
    private int _checkLayoutCounter = 0;

    public void AddGeneratedButton(List<AutoGeneratedButtonModel> buttonModels)
    {
        RectTransform[] containers = GetGeneratedWidgetContainers();
        if (containers.Length <= 0)
        {
            Debug.LogWarning($"auto generated button container in {gameObject.name} is null, unable to auto generate button");
            return;
        }

        ButtonAnimation button = null;
        RectTransform lastContainer = null;
        foreach (var model in buttonModels.OrderBy(model => model.spawnOrder))
        {
            if (model.buttonPrefab == null)
            {
                Debug.LogWarning($"auto generated button prefab for {model.GetIdentifier()} is null");
                continue;
            }

            if (!model.CanGenerate())
            {
                continue;
            }

            RectTransform targetContainer = GetGeneratedWidgetContainer(containers, model.targetContainerIndex);
            if (targetContainer == null)
            {
                Debug.LogWarning($"auto generated button container index {model.targetContainerIndex} in {gameObject.name} is invalid");
                continue;
            }

            if (model.widgetType == AutoGeneratedWidgetType.EntryButton && model.useMenuNavigation)
            {
                button = Instantiate(model.buttonPrefab, targetContainer);
                button.button.onClick = new Button.ButtonClickedEvent();
                button.button.onClick.AddListener(model.InvokeMenuNavigation);
            }
            else if (model.widgetType == AutoGeneratedWidgetType.ActionButton || model.buttonAction != null)
            {
                button = Instantiate(model.buttonPrefab, targetContainer);
                button.button.onClick = new Button.ButtonClickedEvent();
                button.button.onClick.AddListener(model.InvokeButtonAction);
            }
            else
            {
                button = Instantiate(model.buttonPrefab, targetContainer);
                button.button.onClick = model.buttonEvent ?? new Button.ButtonClickedEvent();
            }
            button.text.text = model.buttonLabel;
            button.name = model.GetIdentifier();
            model.generatedButton = button;
            model.onWidgetGenerated?.Invoke(model);
            lastContainer = targetContainer;
        }

        if (button == null || lastContainer == null)
        {
            return;
        }

        _layoutGroup = lastContainer.GetComponent<LayoutGroup>();
        if (_layoutGroup != null)
        {
            FixLayoutAsync(button);
        }
    }

    public RectTransform[] GetGeneratedWidgetContainers()
    {
        if (generatedWidgetContainers != null && generatedWidgetContainers.Length > 0)
        {
            return generatedWidgetContainers.Where(container => container != null).ToArray();
        }

        return mainButtonsContainer != null
            ? new[] { mainButtonsContainer }
            : Array.Empty<RectTransform>();
    }

    private static RectTransform GetGeneratedWidgetContainer(RectTransform[] containers, int containerIndex)
    {
        if (containerIndex < 0 || containerIndex >= containers.Length)
        {
            return null;
        }

        return containers[containerIndex];
    }

    private async void FixLayoutAsync(ButtonAnimation lastButton)
    {
        _checkLayoutCounter = 0;
        _layoutGroup.enabled = false;
        while (!lastButton.gameObject.activeInHierarchy)
        {
            if (_checkLayoutCounter >= MaxCheckLayoutTimeout)
            {
                break;
            }
            await Task.Delay(50);
            _checkLayoutCounter++;
        }
        await Task.Delay(50);
        _layoutGroup.enabled = true;
    }

    public void SetAutogeneratedBtnVisibility(string buttonLabelName, bool isVisible)
    {
        foreach (RectTransform container in GetGeneratedWidgetContainers())
        {
            var btn = container.Find(buttonLabelName);
            if (btn != null)
            {
                btn.gameObject.SetActive(isVisible);
                return;
            }
        }
    }

    protected void ShowLoading(string loadingMessage)
    {
        MenuManager.Instance.HideInfo();
        MenuManager.Instance.ShowLoading(loadingMessage, null, null);
    }

    protected void ShowLoading(
        string loadingMessage,
        string timeoutReachedMessage, 
        int timeoutInSecond,
        UnityAction cancelCallback = null, 
        bool showButton = true, 
        UnityAction okCallback = null, 
        bool disableOkButton = true, 
        string okButtonText = "Ok",
        string cancelButtonText = "Cancel")
    {
        MenuManager.Instance.HideInfo();
        MenuManager.Instance.ShowLoading(loadingMessage,
            new LoadingTimeoutInfo()
            {
                Info = "will timeout in ",
                TimeoutReachedError = timeoutReachedMessage,
                TimeoutSec = timeoutInSecond
            },
            cancelCallback, showButton,
            okCallback, disableOkButton,
            okButtonText, cancelButtonText);
    }

    protected void ShowAdditionalInfo(string loadingMessage, bool hideButton = false)
    {
        MenuManager.Instance.ShowAdditionalInfo(loadingMessage, hideButton);
    }

    protected void ShowError(string errorMessage)
    {
        MenuManager.Instance.HideLoading();
        MenuManager.Instance.ShowInfo(errorMessage, "Error");
    }

    protected void ShowInfo(string infoMessage, string infoTitle="Information")
    {
        MenuManager.Instance.HideLoading();
        MenuManager.Instance.ShowInfo(infoMessage, infoTitle);
    }

    protected void HideLoading(bool showActiveMenuImmediately = true)
    {
        MenuManager.Instance.HideLoading(showActiveMenuImmediately);
    }
}
