using System;
using System.Collections.Generic;
using UnityEngine;

public class MenuHelper
{
    private static readonly Dictionary<MenuCanvas, AutoGeneratedButtonModel[]> _containerAndButtons =
        new Dictionary<MenuCanvas, AutoGeneratedButtonModel[]>();
    private static readonly Dictionary<string, AutoGeneratedButtonModel> _generatedButtonMetadata =
        new Dictionary<string, AutoGeneratedButtonModel>();

    public static void SetGeneratedButtons(AutoGeneratedButtonModel[] buttonModels)
    {
        
    }
    public static void AddGeneratedButton(AutoGeneratedButtonModel[] buttonModels)
    {
        if (buttonModels.Length > 0)
        {
            
        }
    }

    public static Dictionary<MenuCanvas, List<AutoGeneratedButtonModel>> GetContainerAndButtons(Dictionary<TutorialType, ModuleModel> activeModules)
    {
        //set auto generated buttons data
        _generatedButtonMetadata.Clear();
        var containerAndButtons = new Dictionary<MenuCanvas, List<AutoGeneratedButtonModel>>();
        foreach (var activeModule in activeModules)
        {
            var buttonModels = activeModule.Value.autoGeneratedButtonModels;
            if(buttonModels==null)continue;
            foreach (var autoGeneratedButtonModel in buttonModels)
            {
                autoGeneratedButtonModel.ownerTutorialType = activeModule.Key;
                string identifier = autoGeneratedButtonModel.GetIdentifier();
                if(String.IsNullOrWhiteSpace(identifier))continue;
                if (!string.IsNullOrWhiteSpace(autoGeneratedButtonModel.widgetId) &&
                    !_generatedButtonMetadata.TryAdd(autoGeneratedButtonModel.widgetId, autoGeneratedButtonModel))
                {
                    AutoGeneratedButtonModel registeredMetadata = _generatedButtonMetadata[autoGeneratedButtonModel.widgetId];
                    if (registeredMetadata.allowDuplicateWidgetId || autoGeneratedButtonModel.allowDuplicateWidgetId)
                    {
                        continue;
                    }

                    Debug.LogWarning($"Generated widget id '{autoGeneratedButtonModel.widgetId}' is already registered. Skipping duplicate from {activeModule.Key}.");
                    continue;
                }

                var containerPrefab = autoGeneratedButtonModel.targetMenuCanvas;
                if (containerPrefab == null)
                {
                    Debug.LogWarning($"Generated widget '{identifier}' does not have a target menu canvas.");
                    continue;
                }

                if (containerAndButtons.TryGetValue(containerPrefab, out var generatedButtons))
                {
                    generatedButtons.Add(autoGeneratedButtonModel);
                }
                else
                {
                    containerAndButtons.TryAdd(containerPrefab,
                        new List<AutoGeneratedButtonModel>() { autoGeneratedButtonModel });
                }
            }
        }
        return containerAndButtons;
    }

    public static AutoGeneratedButtonModel GetMetadataById(string widgetId)
    {
        if (string.IsNullOrWhiteSpace(widgetId))
        {
            return null;
        }

        _generatedButtonMetadata.TryGetValue(widgetId, out AutoGeneratedButtonModel metadata);
        return metadata;
    }

    public static AutoGeneratedButtonModel GetMetadataById(TutorialType ownerTutorialType, string widgetId)
    {
        AutoGeneratedButtonModel metadata = GetMetadataById(widgetId);
        return metadata != null && metadata.ownerTutorialType == ownerTutorialType ? metadata : null;
    }
}
