// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

using System;
using System.Linq;

public class GConfig
{
    public const string ConfigurationPath = "Modules/TutorialModuleConfig";
    public static string GetSteamAppId()
    {
        var steamConfig = GetSteamConfiguration();
        if (steamConfig != null)
        {
            return steamConfig.steamAppId;
        }
        return string.Empty;
    }

    public static bool GetSteamAutoLogin()
    {
        var steamConfig = GetSteamConfiguration();
        if (steamConfig != null)
        {
            return steamConfig.autoLogin;
        }
        return true;
    }

    public static bool IsSteamEnabled()
    {
        var args = Environment.GetCommandLineArgs();
        if (args.Contains("-nosteam"))
        {
            return false;
        }
        return true;
    }

    private static SteamConfiguration GetSteamConfiguration()
    {
        if (ConfigurationReader.Config != null)
        {
            return ConfigurationReader.Config.steamConfiguration;
        }
        return null;
    }

    public static bool IsUsingAutoGeneratedDeviceID()
    {
        if (ConfigurationReader.Config != null)
        {
            return ConfigurationReader.Config.useAutoGeneratedDeviceIDForLogin;
        }
        return false;
    }

    public static bool IsUsingAMS()
    {
        if (ConfigurationReader.Config != null)
        {
            return ConfigurationReader.Config.multiplayerDSConfiguration.isServerUseAMS;
        }
        return false;
    }
}