using System;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

public enum AutoGeneratedWidgetType
{
    EntryButton = 0,
    ActionButton = 1
}

[Serializable]
public class AutoGeneratedButtonModel
{
    public AutoGeneratedWidgetType widgetType;
    public string widgetId;
    public ButtonAnimation buttonPrefab;
    public string buttonLabel;
    public Button.ButtonClickedEvent buttonEvent;
    public MenuCanvas targetMenuCanvas;
    public int targetContainerIndex;
    public int spawnOrder;
    public bool useMenuNavigation;
    public AssetEnum targetAsset;
    public bool useStarterTargetAsset;
    public AssetEnum starterTargetAsset;
    public TutorialType[] visibilityModuleTypes;
    public bool allowDuplicateWidgetId;

    [NonSerialized] public TutorialType ownerTutorialType;
    [NonSerialized] public ButtonAnimation generatedButton;
    [NonSerialized] public UnityAction buttonAction;
    [NonSerialized] public Func<bool> validateButtonAction;
    [NonSerialized] public Action<AutoGeneratedButtonModel> onWidgetGenerated;

    public bool CanGenerate()
    {
        if (visibilityModuleTypes != null && visibilityModuleTypes.Length > 0)
        {
            bool hasVisibleModule = false;
            foreach (TutorialType visibilityModuleType in visibilityModuleTypes)
            {
                if (TutorialModuleManager.Instance != null &&
                    TutorialModuleManager.Instance.IsModuleActive(visibilityModuleType))
                {
                    hasVisibleModule = true;
                    break;
                }
            }

            if (!hasVisibleModule)
            {
                return false;
            }
        }

        return validateButtonAction?.Invoke() ?? true;
    }

    public void InvokeButtonAction()
    {
        if (!CanGenerate())
        {
            return;
        }

        if (buttonAction == null)
        {
            Debug.LogWarning($"Generated widget '{GetIdentifier()}' does not have a button action.");
            return;
        }

        buttonAction.Invoke();
    }

    public void InvokeMenuNavigation()
    {
        if (!CanGenerate())
        {
            return;
        }

        if (!useMenuNavigation)
        {
            Debug.LogWarning($"Generated widget '{GetIdentifier()}' does not have menu navigation configured.");
            return;
        }

        MenuManager.Instance.ChangeToMenu(GetNavigationTarget());
    }

    private AssetEnum GetNavigationTarget()
    {
        ModuleModel ownerModule = TutorialModuleManager.Instance != null
            ? TutorialModuleManager.Instance.GetModule(ownerTutorialType)
            : null;

        return useStarterTargetAsset && ownerModule != null && ownerModule.isStarterActive
            ? starterTargetAsset
            : targetAsset;
    }

    public string GetIdentifier()
    {
        return string.IsNullOrWhiteSpace(widgetId) ? buttonLabel : widgetId;
    }
}
