using System;
using UnityEngine.UI;

[Serializable]
public class AutoGeneratedButtonModel
{
    public ButtonAnimation buttonPrefab;
    public string buttonLabel;
    public Button.ButtonClickedEvent buttonEvent;
    public MenuCanvas targetMenuCanvas;

}
