using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ModuleModel
{
    public MenuCanvas mainPrefab;
    public MenuCanvas[] additionalPrefab;
    public bool hasAdditionalPrefab;
    public TutorialType type;
    public bool isActive;
    public bool isStarterActive;
    public bool isUIDisable;
    public AutoGeneratedButtonModel[] autoGeneratedButtonModels;
}
